name: PR Code Quality Check

on: [pull_request]

jobs:
  check-docs-and-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run custom checks
        run: |
          pip install -r requirements.txt || true
          python .github/scripts/verify_headers_and_docs.py